---
abstract: 'Add absolute XPath to HTML::Element support'
author:
  - 'HyeonSeung Kim <sng2nara@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Element-AbsoluteXPath
requires:
  HTML::TreeBuilder: 0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/sng2c/HTML-Element-AbsoluteXPath
  repository: https://github.com/sng2c/HTML-Element-AbsoluteXPath.git
version: 0.001
